wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.19
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.2
    t:
      1:
      - 1
      4: 3.8.2
      5: 0.10.19
